/* SUBJECT_NAME | ID
** Mathematics  | 1
** English      | 2
** Science      | 3
** History      | 4
** Geography    | 5
** General      | 6
/* VALUES (BlockID, Difficulty, Subject) */

/* Easy Mathematics */
INSERT INTO EFRQuest.QuestionsDB VALUES (60, 0, 1);
INSERT INTO EFRQuest.QuestionsDB VALUES (61, 0, 1);
/* Hard Mathematics */
INSERT INTO EFRQuest.QuestionsDB VALUES (80, 2, 1);
/* Easy Science */
INSERT INTO EFRQuest.QuestionsDB VALUES (160, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (161, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (162, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (163, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (164, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (165, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (166, 0, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (167, 0, 3);
/* Medium Science */
INSERT INTO EFRQuest.QuestionsDB VALUES (200, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (201, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (202, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (203, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (204, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (205, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (206, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (207, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (208, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (209, 1, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (210, 1, 3);
/* Hard Science */
INSERT INTO EFRQuest.QuestionsDB VALUES (240, 2, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (241, 2, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (242, 2, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (243, 2, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (244, 2, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (245, 2, 3);
INSERT INTO EFRQuest.QuestionsDB VALUES (246, 2, 3);
/* Easy History */
INSERT INTO EFRQuest.QuestionsDB VALUES (120, 0, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (121, 0, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (122, 0, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (123, 0, 4);
/* Medium History */
INSERT INTO EFRQuest.QuestionsDB VALUES (130, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (131, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (132, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (133, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (134, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (135, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (136, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (137, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (138, 1, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (139, 1, 4);
/* Hard History */
INSERT INTO EFRQuest.QuestionsDB VALUES (140, 2, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (141, 2, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (142, 2, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (143, 2, 4);
INSERT INTO EFRQuest.QuestionsDB VALUES (144, 2, 4);
/* Easy Geography */
INSERT INTO EFRQuest.QuestionsDB VALUES (90, 0, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (91, 0, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (92, 0, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (93, 0, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (94, 0, 5);
/* Medium Geography */
INSERT INTO EFRQuest.QuestionsDB VALUES (100, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (101, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (102, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (103, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (104, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (105, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (106, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (107, 1, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (108, 1, 5);
/* Hard Geography */
INSERT INTO EFRQuest.QuestionsDB VALUES (110, 2, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (111, 2, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (112, 2, 5);
INSERT INTO EFRQuest.QuestionsDB VALUES (113, 2, 5);
/* Easy General */
INSERT INTO EFRQuest.QuestionsDB VALUES (1000, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1001, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1002, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1003, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1004, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1005, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1006, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1007, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1008, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1009, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1010, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1011, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1012, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1013, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1014, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1015, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1016, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1017, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1018, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1019, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1020, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1021, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1022, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1023, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1024, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1025, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1026, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1027, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1028, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1029, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1030, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1031, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1032, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1033, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1034, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1035, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1036, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1037, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1038, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1039, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1040, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1041, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1042, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1043, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1044, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1045, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1046, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1047, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1048, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1049, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1050, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1051, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1052, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1053, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1054, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1055, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1056, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1057, 0, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (1058, 0, 6);
/* Medium General */
INSERT INTO EFRQuest.QuestionsDB VALUES (2000, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2001, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2002, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2003, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2004, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2005, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2006, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2007, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2008, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2009, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2010, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2011, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2012, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2013, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2014, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2015, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2016, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2017, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2018, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2019, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2020, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2021, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2022, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2023, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2024, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2025, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2026, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2027, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2028, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2029, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2030, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2031, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2032, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2033, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2034, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2035, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2036, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2037, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2038, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2039, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2040, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2041, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2042, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2043, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2044, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2045, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2046, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2047, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2048, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2049, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2050, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2051, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2052, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2053, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2054, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2055, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2056, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2057, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2058, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2059, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2060, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2061, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2062, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2063, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2064, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2065, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2066, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2067, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2068, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2069, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2070, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2071, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2072, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2073, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2074, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2075, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2076, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2077, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2078, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2079, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2080, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2081, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2082, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2083, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2084, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2085, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2086, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2087, 1, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (2088, 1, 6);
/* Hard General */
INSERT INTO EFRQuest.QuestionsDB VALUES (3000, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3001, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3002, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3003, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3004, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3005, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3006, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3007, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3008, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3009, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3010, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3011, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3012, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3013, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3014, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3015, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3016, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3017, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3018, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3019, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3020, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3021, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3022, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3023, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3024, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3025, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3026, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3027, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3028, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3029, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3030, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3031, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3032, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3033, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3034, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3035, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3036, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3037, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3038, 2, 6);
INSERT INTO EFRQuest.QuestionsDB VALUES (3039, 2, 6);
