export default {
	NONE: undefined,
	EMPTY_FIELDS: "EMPTY_FIELDS",
	INVALID_OBJECT: "INVALID_OBJECT",
	LOGIN_FAIL: "LOGIN_FAIL",
	SIGNUP_FAIL: "SIGNUP_FAIL",
	FETCH_QUESTION_FAIL: "FETCH_QUESTION_FAIL",
	CONN_FAIL: "CONN_FAIL",
	GET_HELP_TIMEOUT: "GET_HELP_TIMEOUT",
	GET_HELP_FAIL: "GET_HELP_FAIL",
	PERSIST_TIMEOUT: "PERSIST_TIMEOUT",
	TIME_OUT: "TIME_OUT"
}