INSERT INTO EFRQuest.Subjects VALUES ('Mathematics');
INSERT INTO EFRQuest.QuestionsDB VALUES (0, 1);
INSERT INTO EFRQuest.QuestionsDB VALUES (0, 1);
INSERT INTO EFRQuest.QuestionsDB VALUES (0, 1);
INSERT INTO EFRQuest.QuestionsDB VALUES (0, 1);
INSERT INTO EFRQuest.QuestionsDB VALUES (0, 1);

INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 10 * 6?', '60', '93', '16', '96', '60', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 11 + 8?', '20', '19', '15', '16', '19', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 21 - 6?', '25', '26', '15', '19', '15', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 6 * 12?', '8', '63', '72', '19', '72', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 8 * 6?', '49', '15', '6', '48', '48', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 8 * 4?', '33', '43', '32', '42', '32', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 12 * 9?', '108', '109', '129', '54', '108', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 11 * 7?', '76', '77', '66', '96', '77', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 1 - 9?', '-9', '-8', '0', '1', '-8', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 24 - 16?', '9', '8', '-8', '7', '8', 1);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 2 * 1?', '44', '8', '3', '2', '2', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 13 * 8?', '105', '0', '100', '104', '104', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 8 * 9?', '73', '72', '64', '62', '72', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 11 - 4?', '7', '6', '9', '3', '7', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 22 - 17?', '6', '15', '5', '16', '5', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 12 * 1?', '1', '12', '24', '14', '12', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 4 * 2?', '16', '14', '8', '12', '8', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 10 - 18?', '-9', '-13', '-8', '14', '-8', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 9 + 5?', '14', '15', '5', '20', '14', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 7 - 19?', '-10', '12', '-12', '-1', '-12', 2);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 8 * 7?', '72', '56', '54', '83', '56', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 10 * 12?', '120', '27', '19', '32', '120', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 11 * 2?', '23', '24', '22', '33', '22', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 10 + 14?', '24', '16', '26', '10', '24', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 4 + 3?', '9', '10', '7', '6', '7', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 8 - 15?', '-7', '8', '-8', '9', '-7', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 1 + 14?', '20', '16', '15', '13', '15', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 3 * 12?', '36', '17', '25', '46', '36', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 4 * 5?', '44', '20', '79', '15', '20', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 10 + 8?', '14', '18', '22', '17', '18', 3);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 15 + 10?', '15', '30', '35', '25', '25', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 9 + 15?', '30', '24', '15', '20', '24', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 5 * 10?', '94', '50', '72', '55', '50', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 3 - 24?', '-18', '-21', '-20', '-17', '-21', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 17 - 4?', '-16', '10', '-13', '13', '13', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 1 * 5?', '6', '0', '5', '1', '5', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 0 * 8?', '8', '1', '0', '9', '0', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 10 - 1?', '8', '10', '-9', '9', '9', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 6 * 2?', '35', '8', '32', '12', '12', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 7 * 5?', '36', '25', '49', '35', '35', 4);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 3 * 10?', '130', '88', '30', '33', '30', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 9 * 9?', '89', '36', '81', '48', '81', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 14 - 1?', '3', '-13', '14', '13', '13', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 12 - 9?', '4', '3', '7', '9', '3', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 19 - 17?', '2', '10', '4', '7', '2', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 18 - 21?', '3', '1', '-3', '-4', '-3', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 2 + 4?', '8', '10', '9', '6', '6', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 7 * 4?', '29', '28', '25', '20', '28', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 8 + 5?', '12', '16', '18', '13', '13', 5);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID) VALUES ('What is 6 * 9?', '54', '55', '60', '61', '54', 5);
