INSERT INTO EFRQuest.QuestionsDB VALUES (10000, 1, 2);

INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('I asked Jane about the accident, but she _____ a word.', 'didn''t use to', 'wouldn''t say', 'shouldn''t say', 'refused', 'wouldn''t say',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('Hang ____! I''ll be there with you an hour.', 'a little', 'down here', 'in there', 'more', 'in there',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('The guest room is quite small, but there should be enough space for you there. You only have a few ____ and pieces.', 'bits', 'clothes', 'stuff', 'books', 'bits',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('If you _____ mind waiting, I''ll call and check if Mr Owen is in.', 'wouldn''t', 'do', 'will', 'could', 'wouldn''t',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('My sister really gets a ____ out of singing in public.', 'fun', 'buzz', 'blush', 'pleasure', 'buzz',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('I''m afraid I _____ used to working in an open-plan office.', 'haven''t ever', 'haven''t', 'haven''t got', 'have', 'haven''t got',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('You ______ him with my wife. She was with me all the time.', 'may have seen', 'mustn''t see', 'can''t have seen', 'should see', 'can''t have seen',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('You are taking this very lightly, ______ your mother is a hamster.', 'whence', 'since', 'as', 'whereas', 'since',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('I’m not sure if I shut down the computer. I can’t really remember _______ it down.', 'have shut', 'shutting', 'to shut', 'I shut', 'shutting',10000, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('I got a _____ box for my birthday.', 'white small wooden', 'small white wooden', 'small wooden white', 'wooden small white', 'small white wooden',10000, NULL);

INSERT INTO EFRQuest.QuestionsDB VALUES (10001, 1, 2);

INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('I know I was supposed to stay serious, but I couldn''t help ______ .', 'to laugh', 'laughed', 'with laughing', 'laughing', 'laughing',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('When making beer, barley is _____ to bring out its sweetness.', 'germinated', 'malting', 'growing', 'produced', 'germinated',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('Everyone wanted to hear the president''s ______ address.', 'inaudible', 'inbound', 'inaugural', 'indented', 'inaugural',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('Our company receives hundreds of ______ emails every day.', 'unstated', 'unsolicited', 'unrequited', 'unkempt', 'unsolicited',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('_____ not been for his help, I couldn''t have passed.', 'If it', 'Was he', 'Had it', 'If he had', 'Had it',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('All the surviors have been ______ for.', 'dealt', 'accounted', 'found', 'reasoned', 'accounted',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('When you are parted from your partner, you _____ to appreciate each other more.', 'find', 'may', 'become', 'grow', 'grow',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('We _____ watch Star Trek with my brother every evening when we were children.', 'had', 'would', 'were used to', 'use to', 'would',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('She’s lost her credit card. She _______ it somewhere.', 'must have been dropping', 'should have dropped', 'must have dropped', 'would have dropped', 'must have dropped',10001, NULL);
INSERT INTO EFRQuest.Questions (QuestionText, QuestionOne, QuestionTwo, QuestionThree, QuestionFour, CorrectAnswer, QuestionBlockID, HelpID) VALUES ('I asked an old couple for directions, but _____ of them knew where the cinema was.', 'all', 'both', 'none', 'neither', 'neither',10001, NULL);
