/****************************************************************************
 * 
 *->Name: Types.js
 *->Purpose: Declare all action types.
 *
*****************************************************************************/

export default {
	Auth: {
		AUTHENTICATING: "AUTHENTICATING",
		AUTHENTICATE_SUCCESSFUL : "AUTHENTICATE_SUCCESS",
		DEAUTHENTICATING : "DEAUTHENTICATING",
		DEAUTHENTICATE_SUCCESSFUL : "DEAUTHENTICATE_SUCCESS",
		RESET : "AUTH_RESET"
	},
	Join: {
		SIGNUP : "SIGNUP",
		SIGNINGUP : "SIGNINGUP",
		SIGNUP_SUCCESSFUL : "SIGN_UP_SUCCESSFUL",
		RESET : "JOIN_RESET"
	},
	User: {
		SOLVED_QUESTION: "SOLVED_QUESTION",
		SET_SESSION_TOKEN : "SET_SESSION_TOKEN",
		SET_USER_OBJECT : "SET_USER_OBJECT",
		SET_COMPLETED : "SET_COMPLETED",
		SET_FNAME : "SET_FNAME",
		SET_LNAME : "SET_LNAME",
		GAME_RESET : "GAME_RESET",
		RESET : "USER_RESET"
	},
	Questions: {
		FETCHED: "FETCHED_QUESTIONS",
		FETCHING: "FETCHING_QUESTIONS",
		FETCHING_HELP: "FETCHING_HELP",
		FETCHED_HELP: "FETCHED_HELP",
		SET_QUESTIONS : "SET_QUESTIONS",
		SET_HELP_TEXT : "SET_HELP_TEXT",
		SET_INDEX : "SET_INDEX",
		SET_ANSWER : "SET_ANSWER",
		SHOW_HELP : "SHOW_HELP",
		HIDE_HELP : "HIDE_HELP",
		RESET : "QUESTION_RESET"
	},
	State: {
		SET_SHOWQUESTION: "SET_SHOWQUESTION",
		SET_PERSIST: "SET_PERSIST",
		SET_SOCKET: "SET_SOCKET",
		SHOW_DASH: "SHOW_DASH",
		SHOW_CHAT: "SHOW_CHAT",
		ERROR : "ERROR",
		REFER : "REFER",
		RESET : "STATE_RESET"
	},
	Messages: {
		SET_TOTAL_USER: "SET_TOTAL_USER",
		SET_MESSAGE: "SET_MESSAGE",
		RESET: "MESSAGE_RESET"
	}
}
