#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EFRFrontEndTest2.Resource", IsApplication=true)]

namespace EFRFrontEndTest2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int font = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderAuthority = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderCerts = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int fontProviderFetchStrategy = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fontProviderFetchTimeout = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderPackage = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderQuery = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int fontStyle = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int fontWeight = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080003
			public const int notification_action_color_filter = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int notification_icon_bg_color = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int notification_material_background_media_default_color = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int primary_text_default_material_dark = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int ripple_material_light = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int secondary_text_default_material_dark = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int secondary_text_default_material_light = 2131230726;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int achievementsBackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BackArrowIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BackgroundGradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BigBubble = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BiologyIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Bubble = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int charity_direct_relief = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int charity_red_cross = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int charity_united_way = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ChemistryIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CreateAccountBackground = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Easygreen = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int favorited = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int filter = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ForwardArrowIcon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int GreenBackgroundGradient = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int GreenButtonIcon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int GreenButtonSelectedIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int GreyButton = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int heartIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int HistoryIcon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int HRBlock = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int LightGreyCircle = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int LoginBackground = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int MathIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Normalyellow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_action_background = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_bg_low = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_bg_low_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_bg_low_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_bg_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_bg_normal_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_icon_background = 2130837538;
			
			// aapt resource value: 0x7f020031
			public const int notification_template_icon_bg = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int notification_template_icon_low_bg = 2130837554;
			
			// aapt resource value: 0x7f020023
			public const int notification_tile_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notify_panel_notification_icon_bg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int OptionsIcon = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int PhysicsIcon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int PurpleExpert = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int redcross2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int RedCrossIcon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int RedHard = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ShuffleIcon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int silverarrow = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int silverarrowright = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int starIcon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int trophyIcon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int unfavorited = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b008c
			public const int AchievementsButton = 2131427468;
			
			// aapt resource value: 0x7f0b007b
			public const int Answer1 = 2131427451;
			
			// aapt resource value: 0x7f0b007c
			public const int Answer2 = 2131427452;
			
			// aapt resource value: 0x7f0b007d
			public const int Answer3 = 2131427453;
			
			// aapt resource value: 0x7f0b007e
			public const int Answer4 = 2131427454;
			
			// aapt resource value: 0x7f0b007f
			public const int BackArrow = 2131427455;
			
			// aapt resource value: 0x7f0b008d
			public const int BackgroundButton = 2131427469;
			
			// aapt resource value: 0x7f0b007a
			public const int BigGrayCircle = 2131427450;
			
			// aapt resource value: 0x7f0b005e
			public const int Buffer = 2131427422;
			
			// aapt resource value: 0x7f0b0044
			public const int CancelButton = 2131427396;
			
			// aapt resource value: 0x7f0b0080
			public const int Continue = 2131427456;
			
			// aapt resource value: 0x7f0b0042
			public const int CreateButton = 2131427394;
			
			// aapt resource value: 0x7f0b004c
			public const int DeleteButton = 2131427404;
			
			// aapt resource value: 0x7f0b0074
			public const int EasyButton = 2131427444;
			
			// aapt resource value: 0x7f0b0032
			public const int EmailBox = 2131427378;
			
			// aapt resource value: 0x7f0b0035
			public const int EmailErrorBox = 2131427381;
			
			// aapt resource value: 0x7f0b003f
			public const int FinalErrorBox = 2131427391;
			
			// aapt resource value: 0x7f0b005b
			public const int ForgotPasswordButton = 2131427419;
			
			// aapt resource value: 0x7f0b0076
			public const int HardButton = 2131427446;
			
			// aapt resource value: 0x7f0b0077
			public const int HardestButton = 2131427447;
			
			// aapt resource value: 0x7f0b0075
			public const int NormalButton = 2131427445;
			
			// aapt resource value: 0x7f0b0036
			public const int PasswordBoxOne = 2131427382;
			
			// aapt resource value: 0x7f0b003b
			public const int PasswordBoxTwo = 2131427387;
			
			// aapt resource value: 0x7f0b003d
			public const int PasswordErrorBox = 2131427389;
			
			// aapt resource value: 0x7f0b008b
			public const int ResetButton = 2131427467;
			
			// aapt resource value: 0x7f0b0034
			public const int TopBox = 2131427380;
			
			// aapt resource value: 0x7f0b0033
			public const int UsernameBox = 2131427379;
			
			// aapt resource value: 0x7f0b0039
			public const int UsernameErrorBox = 2131427385;
			
			// aapt resource value: 0x7f0b000a
			public const int achievementsTitle = 2131427338;
			
			// aapt resource value: 0x7f0b0063
			public const int action0 = 2131427427;
			
			// aapt resource value: 0x7f0b0060
			public const int action_container = 2131427424;
			
			// aapt resource value: 0x7f0b0067
			public const int action_divider = 2131427431;
			
			// aapt resource value: 0x7f0b0061
			public const int action_image = 2131427425;
			
			// aapt resource value: 0x7f0b0062
			public const int action_text = 2131427426;
			
			// aapt resource value: 0x7f0b0071
			public const int actions = 2131427441;
			
			// aapt resource value: 0x7f0b0005
			public const int async = 2131427333;
			
			// aapt resource value: 0x7f0b0078
			public const int backButton = 2131427448;
			
			// aapt resource value: 0x7f0b0019
			public const int back_arrow = 2131427353;
			
			// aapt resource value: 0x7f0b0015
			public const int bigbubble = 2131427349;
			
			// aapt resource value: 0x7f0b0083
			public const int biologyOption = 2131427459;
			
			// aapt resource value: 0x7f0b0006
			public const int blocking = 2131427334;
			
			// aapt resource value: 0x7f0b0090
			public const int bubbleLiveFeedButton = 2131427472;
			
			// aapt resource value: 0x7f0b0014
			public const int bubble_layout = 2131427348;
			
			// aapt resource value: 0x7f0b0054
			public const int buttonCancel = 2131427412;
			
			// aapt resource value: 0x7f0b0053
			public const int buttonSubmit = 2131427411;
			
			// aapt resource value: 0x7f0b0064
			public const int cancel_action = 2131427428;
			
			// aapt resource value: 0x7f0b001e
			public const int charities_list = 2131427358;
			
			// aapt resource value: 0x7f0b0091
			public const int charityButton = 2131427473;
			
			// aapt resource value: 0x7f0b0023
			public const int charity_list = 2131427363;
			
			// aapt resource value: 0x7f0b0016
			public const int charity_selection = 2131427350;
			
			// aapt resource value: 0x7f0b0082
			public const int chemistryOption = 2131427458;
			
			// aapt resource value: 0x7f0b006c
			public const int chronometer = 2131427436;
			
			// aapt resource value: 0x7f0b0079
			public const int continueButton = 2131427449;
			
			// aapt resource value: 0x7f0b005c
			public const int createAccountButton = 2131427420;
			
			// aapt resource value: 0x7f0b0073
			public const int end_padder = 2131427443;
			
			// aapt resource value: 0x7f0b001d
			public const int filter_btn = 2131427357;
			
			// aapt resource value: 0x7f0b0007
			public const int forever = 2131427335;
			
			// aapt resource value: 0x7f0b0030
			public const int frameLayout1 = 2131427376;
			
			// aapt resource value: 0x7f0b0026
			public const int gridLayout1 = 2131427366;
			
			// aapt resource value: 0x7f0b005f
			public const int guestLoginButton = 2131427423;
			
			// aapt resource value: 0x7f0b0012
			public const int heartIcon = 2131427346;
			
			// aapt resource value: 0x7f0b0085
			public const int historyOption = 2131427461;
			
			// aapt resource value: 0x7f0b006e
			public const int icon = 2131427438;
			
			// aapt resource value: 0x7f0b0072
			public const int icon_group = 2131427442;
			
			// aapt resource value: 0x7f0b004e
			public const int imageButton1 = 2131427406;
			
			// aapt resource value: 0x7f0b004f
			public const int imageButton2 = 2131427407;
			
			// aapt resource value: 0x7f0b0050
			public const int imageButton3 = 2131427408;
			
			// aapt resource value: 0x7f0b0051
			public const int imageButton4 = 2131427409;
			
			// aapt resource value: 0x7f0b0031
			public const int imageView1 = 2131427377;
			
			// aapt resource value: 0x7f0b0058
			public const int imageView2 = 2131427416;
			
			// aapt resource value: 0x7f0b006d
			public const int info = 2131427437;
			
			// aapt resource value: 0x7f0b0021
			public const int info_btn = 2131427361;
			
			// aapt resource value: 0x7f0b0008
			public const int italic = 2131427336;
			
			// aapt resource value: 0x7f0b0049
			public const int lableUsername = 2131427401;
			
			// aapt resource value: 0x7f0b0057
			public const int layout = 2131427415;
			
			// aapt resource value: 0x7f0b000d
			public const int level = 2131427341;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0047
			public const int linearLayout1 = 2131427399;
			
			// aapt resource value: 0x7f0b0017
			public const int linearLayout2 = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int linearLayout3 = 2131427352;
			
			// aapt resource value: 0x7f0b001a
			public const int linearLayout4 = 2131427354;
			
			// aapt resource value: 0x7f0b001c
			public const int linearLayout5 = 2131427356;
			
			// aapt resource value: 0x7f0b004a
			public const int linearLayoutButtons = 2131427402;
			
			// aapt resource value: 0x7f0b004d
			public const int linearLayoutCancel = 2131427405;
			
			// aapt resource value: 0x7f0b004b
			public const int linearLayoutSubmit = 2131427403;
			
			// aapt resource value: 0x7f0b005d
			public const int loginButton = 2131427421;
			
			// aapt resource value: 0x7f0b0056
			public const int lvLabel = 2131427414;
			
			// aapt resource value: 0x7f0b000b
			public const int lvLayout = 2131427339;
			
			// aapt resource value: 0x7f0b0084
			public const int mathOption = 2131427460;
			
			// aapt resource value: 0x7f0b0066
			public const int media_actions = 2131427430;
			
			// aapt resource value: 0x7f0b0011
			public const int moneyLayout = 2131427345;
			
			// aapt resource value: 0x7f0b0013
			public const int moneyRaised = 2131427347;
			
			// aapt resource value: 0x7f0b0087
			public const int music = 2131427463;
			
			// aapt resource value: 0x7f0b0009
			public const int normal = 2131427337;
			
			// aapt resource value: 0x7f0b0089
			public const int note1 = 2131427465;
			
			// aapt resource value: 0x7f0b008a
			public const int note2 = 2131427466;
			
			// aapt resource value: 0x7f0b0070
			public const int notification_background = 2131427440;
			
			// aapt resource value: 0x7f0b0069
			public const int notification_main_column = 2131427433;
			
			// aapt resource value: 0x7f0b0068
			public const int notification_main_column_container = 2131427432;
			
			// aapt resource value: 0x7f0b005a
			public const int passwordBox = 2131427418;
			
			// aapt resource value: 0x7f0b0081
			public const int physicsOption = 2131427457;
			
			// aapt resource value: 0x7f0b008e
			public const int playButton = 2131427470;
			
			// aapt resource value: 0x7f0b000e
			public const int questionLayout = 2131427342;
			
			// aapt resource value: 0x7f0b0010
			public const int questionsAnswered = 2131427344;
			
			// aapt resource value: 0x7f0b006f
			public const int right_icon = 2131427439;
			
			// aapt resource value: 0x7f0b006a
			public const int right_side = 2131427434;
			
			// aapt resource value: 0x7f0b0024
			public const int save_btn = 2131427364;
			
			// aapt resource value: 0x7f0b0025
			public const int save_btn_ext = 2131427365;
			
			// aapt resource value: 0x7f0b0022
			public const int scrollview1 = 2131427362;
			
			// aapt resource value: 0x7f0b0020
			public const int selected_charitiy_name = 2131427360;
			
			// aapt resource value: 0x7f0b002a
			public const int setblue = 2131427370;
			
			// aapt resource value: 0x7f0b002d
			public const int setdarkblue = 2131427373;
			
			// aapt resource value: 0x7f0b002f
			public const int setdarkgreen = 2131427375;
			
			// aapt resource value: 0x7f0b002e
			public const int setdarkred = 2131427374;
			
			// aapt resource value: 0x7f0b002b
			public const int setgray = 2131427371;
			
			// aapt resource value: 0x7f0b0029
			public const int setgreen = 2131427369;
			
			// aapt resource value: 0x7f0b002c
			public const int setpurple = 2131427372;
			
			// aapt resource value: 0x7f0b0028
			public const int setred = 2131427368;
			
			// aapt resource value: 0x7f0b008f
			public const int settingsButton = 2131427471;
			
			// aapt resource value: 0x7f0b0086
			public const int shuffleOption = 2131427462;
			
			// aapt resource value: 0x7f0b0088
			public const int sound = 2131427464;
			
			// aapt resource value: 0x7f0b000c
			public const int starIcon = 2131427340;
			
			// aapt resource value: 0x7f0b0065
			public const int status_bar_latest_event_content = 2131427429;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b0052
			public const int textUsername = 2131427410;
			
			// aapt resource value: 0x7f0b0027
			public const int textView1 = 2131427367;
			
			// aapt resource value: 0x7f0b0040
			public const int textView10 = 2131427392;
			
			// aapt resource value: 0x7f0b0041
			public const int textView11 = 2131427393;
			
			// aapt resource value: 0x7f0b0043
			public const int textView12 = 2131427395;
			
			// aapt resource value: 0x7f0b0045
			public const int textView14 = 2131427397;
			
			// aapt resource value: 0x7f0b0046
			public const int textView15 = 2131427398;
			
			// aapt resource value: 0x7f0b001b
			public const int textView2 = 2131427355;
			
			// aapt resource value: 0x7f0b001f
			public const int textView3 = 2131427359;
			
			// aapt resource value: 0x7f0b0037
			public const int textView4 = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int textView5 = 2131427384;
			
			// aapt resource value: 0x7f0b003a
			public const int textView6 = 2131427386;
			
			// aapt resource value: 0x7f0b003c
			public const int textView7 = 2131427388;
			
			// aapt resource value: 0x7f0b003e
			public const int textView8 = 2131427390;
			
			// aapt resource value: 0x7f0b006b
			public const int time = 2131427435;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			// aapt resource value: 0x7f0b0048
			public const int titleForgotPassword = 2131427400;
			
			// aapt resource value: 0x7f0b0055
			public const int titleLevelUp = 2131427413;
			
			// aapt resource value: 0x7f0b000f
			public const int trophyIcon = 2131427343;
			
			// aapt resource value: 0x7f0b0059
			public const int usernameBox = 2131427417;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int cancel_button_image_alpha = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int status_bar_notification_info_maxnum = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AchievementsPage = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BubbleLiveFeed = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CharityFilterPage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CharitySelectionScreen = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ColorPicker = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int CreateAccountScreen = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int DeleteDataPopup = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int DifficultyPage = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ForgotPasswordAlertDialogScreen = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int LevelUp = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int LoginPageScreen = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_action = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_action_tombstone = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_media_action = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_media_cancel_action = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_big_media = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_big_media_custom = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_template_big_media_narrow = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int notification_template_big_media_narrow_custom = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_template_custom_big = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int notification_template_icon_group = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int notification_template_lines_media = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int notification_template_media = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int notification_template_media_custom = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int notification_template_part_chronometer = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int notification_template_part_time = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int QuestionDifficultypage = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int QuestionsPage = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int SelectSubjectScreen = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int settingsPage = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int UserDashboardScreen = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int WinPage = 2130968607;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int efr2icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int efr3icon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int efr4icon = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int efr5icon = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int efricon = 2130903044;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int changeImage = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int status_bar_notification_info_overflow = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Info = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int TextAppearance_Compat_Notification_Line2 = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Media = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Time = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int TextAppearance_Compat_Notification_Title = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int Widget_Compat_NotificationActionContainer = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Widget_Compat_NotificationActionText = 2131165195;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] FontFamily = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
