#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EFRFrontEndTest2.Resource", IsApplication=true)]

namespace EFRFrontEndTest2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int achievementsBackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BackArrowIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BackgroundGradient = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BigBubble = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BiologyIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Bubble = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ChemistryIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ForwardArrowIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int GreenBackgroundGradient = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int GreenButtonIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int GreenButtonSelectedIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int GreyButton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int heartIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int HistoryIcon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int HRBlock = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int LightGreyCircle = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MathIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Normalstar = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int OptionsIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int PhysicsIcon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int PurpleStar = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int redcross2 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int RedCrossIcon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int RedStar = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ShuffleIcon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int silverarrow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int StarGreen = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int starIcon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int trophyIcon = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060047
			public const int Answer1 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int Answer2 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int Answer3 = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int Answer4 = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int BackArrow = 2131099723;
			
			// aapt resource value: 0x7f060046
			public const int BigGrayCircle = 2131099718;
			
			// aapt resource value: 0x7f060026
			public const int CancelButton = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int CreateButton = 2131099684;
			
			// aapt resource value: 0x7f060041
			public const int EasyButton = 2131099713;
			
			// aapt resource value: 0x7f060013
			public const int EmailBox = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int EmailErrorBox = 2131099671;
			
			// aapt resource value: 0x7f060021
			public const int FinalErrorBox = 2131099681;
			
			// aapt resource value: 0x7f06003e
			public const int ForgotPasswordButton = 2131099710;
			
			// aapt resource value: 0x7f060043
			public const int HardButton = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int HardestButton = 2131099716;
			
			// aapt resource value: 0x7f060015
			public const int MaxCharErrorBox = 2131099669;
			
			// aapt resource value: 0x7f060042
			public const int NormalButton = 2131099714;
			
			// aapt resource value: 0x7f060018
			public const int PasswordBoxOne = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int PasswordBoxTwo = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int PasswordErrorBox = 2131099679;
			
			// aapt resource value: 0x7f060056
			public const int ResetButton = 2131099734;
			
			// aapt resource value: 0x7f060014
			public const int UsernameBox = 2131099668;
			
			// aapt resource value: 0x7f06001b
			public const int UsernameErrorBox = 2131099675;
			
			// aapt resource value: 0x7f060000
			public const int achievementsTitle = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int backButton = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int bigbubble = 2131099659;
			
			// aapt resource value: 0x7f06004e
			public const int biologyOption = 2131099726;
			
			// aapt resource value: 0x7f060037
			public const int bubbleLiveFeedButton = 2131099703;
			
			// aapt resource value: 0x7f06000a
			public const int bubble_layout = 2131099658;
			
			// aapt resource value: 0x7f060034
			public const int buttonCancel = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int buttonSubmit = 2131099698;
			
			// aapt resource value: 0x7f060038
			public const int charityButton = 2131099704;
			
			// aapt resource value: 0x7f06004d
			public const int chemistryOption = 2131099725;
			
			// aapt resource value: 0x7f060045
			public const int continueButton = 2131099717;
			
			// aapt resource value: 0x7f060040
			public const int createAccountButton = 2131099712;
			
			// aapt resource value: 0x7f060011
			public const int frameLayout1 = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int gridLayout1 = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int heartIcon = 2131099656;
			
			// aapt resource value: 0x7f060050
			public const int historyOption = 2131099728;
			
			// aapt resource value: 0x7f060029
			public const int imageButton1 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int imageButton2 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int imageButton3 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int imageButton4 = 2131099692;
			
			// aapt resource value: 0x7f060012
			public const int imageView1 = 2131099666;
			
			// aapt resource value: 0x7f06003a
			public const int imageView2 = 2131099706;
			
			// aapt resource value: 0x7f06002e
			public const int lableUsername = 2131099694;
			
			// aapt resource value: 0x7f060039
			public const int layout = 2131099705;
			
			// aapt resource value: 0x7f060003
			public const int level = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f060030
			public const int linearLayoutButtons = 2131099696;
			
			// aapt resource value: 0x7f060033
			public const int linearLayoutCancel = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int linearLayoutSubmit = 2131099697;
			
			// aapt resource value: 0x7f06003f
			public const int loginButton = 2131099711;
			
			// aapt resource value: 0x7f060001
			public const int lvLayout = 2131099649;
			
			// aapt resource value: 0x7f06004f
			public const int mathOption = 2131099727;
			
			// aapt resource value: 0x7f060007
			public const int moneyLayout = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int moneyRaised = 2131099657;
			
			// aapt resource value: 0x7f060052
			public const int music = 2131099730;
			
			// aapt resource value: 0x7f060054
			public const int note1 = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int note2 = 2131099733;
			
			// aapt resource value: 0x7f06003d
			public const int passwordBox = 2131099709;
			
			// aapt resource value: 0x7f06004c
			public const int physicsOption = 2131099724;
			
			// aapt resource value: 0x7f060035
			public const int playButton = 2131099701;
			
			// aapt resource value: 0x7f060004
			public const int questionLayout = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int questionsAnswered = 2131099654;
			
			// aapt resource value: 0x7f060036
			public const int settingsButton = 2131099702;
			
			// aapt resource value: 0x7f060051
			public const int shuffleOption = 2131099729;
			
			// aapt resource value: 0x7f060053
			public const int sound = 2131099731;
			
			// aapt resource value: 0x7f060002
			public const int starIcon = 2131099650;
			
			// aapt resource value: 0x7f06002f
			public const int textUsername = 2131099695;
			
			// aapt resource value: 0x7f06000f
			public const int textView1 = 2131099663;
			
			// aapt resource value: 0x7f060022
			public const int textView10 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int textView11 = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int textView12 = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int textView14 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int textView15 = 2131099688;
			
			// aapt resource value: 0x7f06003c
			public const int textView2 = 2131099708;
			
			// aapt resource value: 0x7f060016
			public const int textView3 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int textView4 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int textView5 = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int textView6 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int textView7 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int textView8 = 2131099680;
			
			// aapt resource value: 0x7f06002d
			public const int titleForgotPassword = 2131099693;
			
			// aapt resource value: 0x7f060005
			public const int trophyIcon = 2131099653;
			
			// aapt resource value: 0x7f06003b
			public const int usernameBox = 2131099707;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AchievementsPage = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BubbleLiveFeed = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CharitySelectionScreen = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CreateAccountScreen = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int DifficultyPage = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ForgotPasswordAlertDialogScreen = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int HomeScreen = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Main = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int QuestionDifficultypage = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int QuestionsPage = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int SelectSubjectScreen = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int settingsPage = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int WinPage = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int efr2icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int efr3icon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int efr4icon = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int efr5icon = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int efricon = 2130903044;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int changeImage = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
